# Global 全局配置
site_analytics: ''
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: ''
snow: true
click_animate_js: 'candy'
enable_dark: false
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
check_update: false

vendors:
  packages:
    disqusjs: 
      version: 1.2.6
    gitalk: 
      version: 1.7.2
    gitment: 
      version: 0.0.3
    twikoo: 
      version: 1.5.11
    valine: 
      version: 1.4.18
    "@waline/client": 
      version: 1.6.0
    bootstrap: 
      version: 3.3.4
    nprogress: 
      version: 0.2.0
    aplayer: 
      version: 1.10.1
    "@fancyapps/fancybox": 
      version: 3.5.7
    clipboard: 
      version: 2.0.6
    layui-src: 
      version: 2.5.5
    font-awesome: 
      version: 4.7.0
    jquery: 
      version: 3.6.0
    qrcode_js: 
      version: 1.0.0
    mermaid: 
      version: 9.1.1
    meting:
      version: 2.0.1

# 自定义样式
customStyles:
  images: # 图片相关设置
    banner: /Images/th.jpg # 站点横幅
    background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: true
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  archives: /archives/
  friends: /friends/
  # sites:
  #   submenu: true
  #   author: https://candinya.com
  #   project: https://github.com/Candinya/Kratos-Rebirth

label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>档案馆
  friends: <i class="fa fa-paw"></i>友情链接
  # sites:
  #   submenu: <i class="fa fa-link"></i>链接
  #   author: 作者博客
  #   project: 项目链接

# Footer 页脚配置
group_link: 
contact:
  weibo: 
  mail: 1744793737@qq.com 
  telegram:
  twitter: '@XiaoDeng3386'
  facebook: 
  linkedin: 
  fediverse:
    instance: 
    username: 
  github: This-is-XiaoDeng
  rss: "/atom.xml"
timenotice: 本站已运行
icp: 萌ICP备20220786号 
psr:
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: false
  share: true
  comments: 
    provider: 'gitalk'
    enableBGImage: false

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: #后端服务器地址，必填
  visitor: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'cc7598f4302064fcc288'
  clientSecret: '3a8665a200f6780befa2382f846eb2ee45749c97'
  repo: 'Blog'
  owner: 'This-is-XiaoDeng'
  admin: 
    - 'This-is-XiaoDeng'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'This-is-XiaoDeng'
  repo: 'This-is-XiaoDeng/Blog'
  oauth:
    client_id: 'cc7598f4302064fcc288'
    client_secret: '3a8665a200f6780befa2382f846eb2ee45749c97'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid:

# APlayer 左下角音乐播放器
aplayer:
  enabled: false
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 3204190542
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /Images/2.jpeg
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20
      baseUrl: null # 使用默认值（不单独配置），将跟随 vendors 中的相关设定选择是否使用 cdn
      filenameTemplate: "thumb_{no}.webp" 
    createTime: "2021/11/26 17:03:12"
    donateBtn: 
    scanNotice:
    qr_alipay: 
    qr_wechat: 
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "友情链接"
    comments: false
    description: "友情链接"
    updated: "2023-01-02"
  list:
    - name: "IT Craft Development Team"
      bio: "IT Craft Development Team Website"
      avatar: "https://www.itcdt.top/file/QQ_Image_1664966405883.jpg"
      link: "https://itcdt.top"
    - name: "XieXiLin"
      bio: "XieXiLin's Home"
      avatar: "https://www.xiexilin.cn/favicon.ico"
      link: "https://www.xiexilin.cn"
    - name: "YiFanZhuZhu"
      bio: "YiFanZhuZhu's Blog"
      avatar: "https://blog.yifanzhuzhu.tk/images/favicon-32x32-yf.png"
      link: "https://blog.yifanzhuzhu.tk/"
  verify: true # 验证每个友链的可访问性，炸了会有提示
